import { Router, Response } from 'express'
import { authenticate, AuthRequest } from '../middleware/auth'
import { prisma } from '../lib/prisma'
import PDFDocument from 'pdfkit'
import Groq from 'groq-sdk'
import { MODELS } from '../lib/aiUtils'

export const documentsRouter = Router()
documentsRouter.use(authenticate)

let _groq: Groq | null = null
function getGroq() {
  if (_groq) return _groq
  const key = process.env.GROQ_API_KEY
  if (!key) throw new Error('GROQ_API_KEY not set')
  _groq = new Groq({ apiKey: key })
  return _groq
}

documentsRouter.get('/export/:dealId', async (req: AuthRequest, res: Response) => {
  try {
    const { dealId } = req.params

    const deal = await prisma.deal.findUnique({
      where: { id: dealId, companyId: req.user!.companyId },
      include: {
        client: true,
      }
    })

    if (!deal) {
      res.status(404).json({ error: 'Deal not found' })
      return
    }

    // AI Generation of Executive Summary
    let aiSummary = 'Detailed financial report for deal processing.'
    try {
      const groq = getGroq()
      const prompt = `You are a financial analyst. Write a professional, concise executive summary (3-4 sentences) for this ${deal.stage === 'closed_won' ? 'successful' : 'unsuccessful'} deal in the GCC region.
      Deal: ${deal.title}
      Company: ${deal.company}
      Final Value: AED ${deal.value.toString()}
      Client Notes: ${deal.client?.notes || 'N/A'}
      
      Focus on the financial impact and strategic value. Tone: Professional and data-driven.`

      const completion = await groq.chat.completions.create({
        model: MODELS.LARGE,
        messages: [{ role: 'user', content: prompt }],
        max_tokens: 300,
        temperature: 0.7
      })
      aiSummary = completion.choices[0]?.message?.content || aiSummary
    } catch (aiErr) {
      console.error('AI Summary failed, using fallback:', aiErr)
    }

    // Set headers for PDF download
    res.setHeader('Content-Type', 'application/pdf')
    res.setHeader('Content-Disposition', `attachment; filename=deal_${deal.id}_summary.pdf`)

    // Create a new PDF document
    const doc = new PDFDocument({ margin: 50 })
    doc.pipe(res)

    // Design
    doc.rect(0, 0, doc.page.width, 100).fill('#0f172a') // Header (Slate-900)
    
    doc.fillColor('#ffffff')
       .fontSize(20)
       .text('AI DEAL SUMMARY REPORT', 50, 40)
    
    doc.fontSize(10)
       .text(`Reference: ${deal.id.toUpperCase()}`, 50, 65)
       .text(`Generated: ${new Date().toLocaleString()}`, 50, 80)

    doc.moveDown(4)

    // AI Executive Summary Section
    doc.fillColor('#0f172a')
       .fontSize(16)
       .text('AI Executive Analysis', { underline: true })
    doc.moveDown(0.5)
    doc.fillColor('#334155')
       .fontSize(11)
       .text(aiSummary, { align: 'justify', lineGap: 2 })
    
    doc.moveDown(2)

    // Financial Details
    doc.fillColor('#0f172a')
       .fontSize(16)
       .text('Financial Breakdown', { underline: true })
    doc.moveDown(0.5)

    const tableTop = doc.y
    doc.fontSize(11).fillColor('#64748b')
    doc.text('Metric', 50, tableTop)
    doc.text('Value', 300, tableTop)
    
    doc.moveTo(50, tableTop + 15).lineTo(500, tableTop + 15).stroke('#e2e8f0')
    
    const rows = [
      ['Deal Title', deal.title],
      ['Company', deal.company],
      ['Final Transaction Value', `AED ${parseFloat(deal.value.toString()).toLocaleString()}`],
      ['Deal Status', deal.stage.toUpperCase()],
      ['Closed Date', new Date(deal.closedDate).toLocaleDateString()]
    ]

    let currentY = tableTop + 25
    rows.forEach(([label, value]) => {
      doc.fillColor('#475569').text(label, 50, currentY)
      doc.fillColor('#0f172a').font('Helvetica-Bold').text(value, 300, currentY).font('Helvetica')
      currentY += 20
    })

    if (deal.client) {
      doc.moveDown(2)
      doc.fillColor('#0f172a')
         .fontSize(16)
         .text('Client Context', { underline: true })
      doc.moveDown(0.5)
      doc.fontSize(11).fillColor('#475569')
         .text(`Account: ${deal.client.name}`)
         .text(`Region: ${deal.client.country || 'GCC'}`)
         .text(`Industry: ${deal.client.industry || 'B2B'}`)
    }

    // Footer
    doc.rect(0, doc.page.height - 50, doc.page.width, 50).fill('#f8fafc')
    doc.fillColor('#94a3b8')
       .fontSize(9)
       .text('This document was generated by the GCC360 AI Reporting Agent.', 50, doc.page.height - 35, { align: 'center' })

    doc.end()

  } catch (error: any) {
    console.error('PDF generation error:', error)
    if (!res.headersSent) {
      res.status(500).json({ error: 'Failed to generate PDF' })
    }
  }
})
